### ISSUE TITLE
Request to add new arm64/v8 architecture

### ISSUE THREAD

**Issue by fuzzyoung** [alexandzors/caddy#2]
Request to add a new arm64/v8 architecture for the image for OrangePi Zero2W devices. I will be grateful!

**Comment by alexandzors** [comment]
I did not forget about this! Currently working through some AWS training for work. Hoping to get to this next week.

**Comment by alexandzors** [comment]
@fuzzyoung I think I have a working image though not sure since I do not have an arm based docker system to test. Would you like to test it for me?

**Comment by fuzzyoung** [comment]
> @fuzzyoung I think I have a working image though not sure since I do not have an arm based docker system to test. Would you like to test it for me?

Of course, I'll be happy to test it! We can try if it will work

**Comment by alexandzors** [comment]
Awesome! I am testing the build process in a temp repo at the moment. Once I get the build workflow file finalized I'll upload to this repo and ping you with the tag to pull.

**Comment by fuzzyoung** [comment]
> Awesome! I am testing the build process in a temp repo at the moment. Once I get the build workflow file finalized I'll upload to this repo and ping you with the tag to pull.

Great, I'll wait then

**Comment by alexandzors** [comment]
Can you try pulling the alexandzors/caddy:v2.7.6-arm64 image?

**Comment by alexandzors** [comment]
@fuzzyoung looks like the arm binary works on my rpi4 so the container should be working 🤞 

![image](https://github.com/alexandzors/caddy/assets/25626115/997de8ec-eb57-4791-b891-91a94b6dae37)

**Comment by alexandzors** [comment]
Since I did not hear back I'm going to close this. If the image is not working please let me know!
